-- 量化选债命中表扩展：添加退出跟踪字段
-- 使回填和实时选债的结果与回测完全一致

ALTER TABLE quant_screen_hits 
    ADD COLUMN IF NOT EXISTS exit_time VARCHAR(20) DEFAULT NULL COMMENT '退出时间(HH:MM:SS)',
    ADD COLUMN IF NOT EXISTS exit_price FLOAT DEFAULT NULL COMMENT '退出价格',
    ADD COLUMN IF NOT EXISTS profit_pct FLOAT DEFAULT NULL COMMENT '盈亏百分比',
    ADD COLUMN IF NOT EXISTS exit_reason VARCHAR(20) DEFAULT NULL COMMENT '退出原因(tp/sl/timeout)',
    ADD COLUMN IF NOT EXISTS hold_seconds INT DEFAULT NULL COMMENT '持仓秒数',
    ADD COLUMN IF NOT EXISTS max_price FLOAT DEFAULT NULL COMMENT '持仓期间最高价',
    ADD COLUMN IF NOT EXISTS min_price FLOAT DEFAULT NULL COMMENT '持仓期间最低价';
