#!/usr/bin/env python
"""检查 2026-05-19 所有时间点的 star_color 和条件数据"""
import sys
sys.path.insert(0, 'F:\\pyworkspace2026\\gs2026\\src')

from gs2026.utils import config_util
from sqlalchemy import create_engine, text
import json

url = config_util.get_config('common.url')
engine = create_engine(url, pool_recycle=3600, pool_pre_ping=True, connect_args={'connect_timeout': 10})

with engine.connect() as conn:
    # 查询 09:41:33 的记录
    result = conn.execute(text("""
        SELECT stock_code, stock_name, level, star_color, market_context, conditions
        FROM buy_point_candidates 
        WHERE date = '2026-05-19' AND time = '09:41:33'
    """))
    rows = result.fetchall()
    
    print(f"=== 2026-05-19 09:41:33 ===")
    print(f"Records: {len(rows)}")
    for r in rows:
        print(f"\nCode: {r[0]}, Name: {r[1]}, Level: {r[2]}, StarColor: {r[3]}")
        
        # market_context
        mkt = r[4]
        if mkt:
            mkt_data = json.loads(mkt) if isinstance(mkt, str) else mkt
            print(f"  criticalHit: {mkt_data.get('criticalHit', 'NOT SET')}")
            print(f"  passed: {mkt_data.get('passed')}/{mkt_data.get('total')}")
            print(f"  signal: {mkt_data.get('signal')}")
            conds = mkt_data.get('conditions', [])
            for c in conds:
                print(f"    - {c.get('name')}: {'PASS' if c.get('passed') else 'FAIL'}")
        
        # conditions
        conds = r[5]
        if conds:
            cond_data = json.loads(conds) if isinstance(conds, str) else conds
            print(f"  Stock conditions:")
            for c in cond_data:
                print(f"    - {c.get('name')}: {'PASS' if c.get('passed') else 'FAIL'}")

    # 检查这条记录是由回溯生成的还是实时生成的
    print(f"\n=== Check if record was regenerated by backtest ===")
    result = conn.execute(text("""
        SELECT star_color, COUNT(*) as cnt 
        FROM buy_point_candidates 
        WHERE date = '2026-05-19'
        GROUP BY star_color
    """))
    for r in result.fetchall():
        print(f"  star_color={r[0]}: {r[1]} records")
